### modeljieshi
model_name_or_path: /remote-home/xiaoyili/2025-Medical/model/Qwen/Qwen2___5-1___5B

### method
stage: sft
do_train: true
finetuning_type: full
# deepspeed: examples/deepspeed/ds_z3_config.json
deepspeed: /remote-home/xiaoyili/2025-Medical/LLaMA-Factory/examples/deepspeed/ds_z3_config.json

### dataset
# dataset: huatuo_26m_lite_score_5
dataset_dir: /remote-home/xiaoyili/2025-Medical/LLaMA-Factory/data
dataset: huatuo_26m_lite_score_5_alpaca_3*500_filtered_ifd_1.1_rifd_2_60%
template: qwen
cutoff_len: 512
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /remote-home/xiaoyili/2025-Medical/LLaMA-Factory/lxy/saves/qwen2.5-1.5b/full/sft
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
flash_attn: fa2
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 200